# Generated by Django 5.1.2 on 2024-10-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsor",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="F.I.SH"),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="organization_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="TASHKILOT NOMI"
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="other_payment_amount",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="BOSHQA SUMMA"
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="payment_amount",
            field=models.CharField(
                choices=[
                    (1000000, "1 000 000 UZS"),
                    (5000000, "5 000 000 UZS"),
                    (7000000, "7 000 000 UZS"),
                    (10000000, "10 000 000 UZS"),
                    (30000000, "30 000 000 UZS"),
                    ("other", "Boshqa"),
                ],
                max_length=50,
                verbose_name="TO'LOV SUMMASI",
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[("pul", "Pul o`tkazmalari")],
                max_length=50,
                null=True,
                verbose_name="TO`LOV TURI",
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="person_type",
            field=models.CharField(
                choices=[("jismoniy", "Jismoniy Shaxs"), ("yuridik", "Yuridik Shaxs")],
                max_length=10,
                verbose_name="SHAXS",
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="phone_number",
            field=models.CharField(
                max_length=13, verbose_name="TELEFON RAQAMINGIZ:+998"
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="spent_amount",
            field=models.PositiveIntegerField(
                default=0, verbose_name="SARFLANGAN SUMMA"
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="status",
            field=models.CharField(
                choices=[
                    ("yangi", "Yangi"),
                    ("tasdiqlangan", "Tasdiqlangan"),
                    ("bekor_qilingan", "Bekor qilingan"),
                    ("moderatsiya", "Moderatsiyada"),
                ],
                default="yangi",
                max_length=20,
                verbose_name="HOLATI",
            ),
        ),
    ]
